### ISSUE TITLE
Classic/Split View

### ISSUE THREAD

**Issue by eim3** [willwull/saturnus#91]
Can you add split view like the ones you on reddit uwp apps? Simply using a mobile-esque UI on a desktop is a waste of screen real estate imo.

Attached below is a screenshot from the addon "SHINE for reddit". It also had a classic view but the images and comments road right below the post when you click on it. (you can see the view modes in the top mid of the screenshot)

![firefox_2018-01-24_04-56-04](https://user-images.githubusercontent.com/33675519/83913378-04254480-a78d-11ea-879a-845d9b654ae6.png)

Good work btw, love how smooth it is.

**Comment by willwull** [comment]
Hey @eim3! Really sorry about the late reply, completely missed this (over half a year later lol...)

To answer your question: I'm currently not actively working on this project at the moment since I'm busy with other stuff (work, other projects etc) and when eventually come back to this project I will probably first focus on adding core features that are still missing (posting, commenting, etc).

And to be completely honest I'm personally not a fan of those types of layouts so while your comment about waste of real-estate makes sense I think it would actually require a lot of changes, so I don't see myself prioritizing this :/

Sorry that the answer is not what you're looking for, but thank you for the suggestion!
